Update python-package-conda.yml

diff --git a/.github/workflows/python-package-conda.yml b/.github/workflows/python-package-conda.yml
--- a/.github/workflows/python-package-conda.yml
+++ b/.github/workflows/python-package-conda.yml
@@ -28,7 +28,13 @@ jobs:
         source activate env_${{ matrix.python-version }}
 
     - name: Install dependencies
-      run: conda env update --file environment.yml
+      run: |
+        if [ -f environment.yml ]; then
+          conda env update --file environment.yml --name env_${{ matrix.python-version }}
+        else
+          echo "environment.yml not found!"
+          exit 1
+        fi
 
     - name: Lint with flake8
       run: |
@@ -42,7 +48,7 @@ jobs:
         pytest --junitxml=results.xml
 
     - name: Upload test results
-      uses: actions/upload-artifact@v4
+      uses: actions/upload-artifact@v3
       with:
         name: test-results
         path: results.xml
